<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RootNamespace>EnvManager</RootNamespace>
    <AssemblyName>EnvManager</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="YamlDotNet" />
    <PackageReference Include="GitVersion.MsBuild">
      <PrivateAssets>All</PrivateAssets>
   </PackageReference>

  </ItemGroup>
    

</Project>
